# Database Configuration (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/exp7_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC
spring.datasource.username=root
spring.datasource.password=root
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# Hibernate/JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# JWT Secret (Should be moved to environment variable in prod)
jwt.secret=7d82f3a63b0a2f43b59301f21501d51a629b3c4f74d0e82c5a27129f12345678
jwt.expiration=3600000
